import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/page";
import "@/lib/fontawesome"; // import your setup
import { config } from "@fortawesome/fontawesome-svg-core";
import { Toaster } from "@/components/ui/sonner";
import Footer from "./_components/footer/footer";
import MySessionProvider from "@/SessionProvider/mySessionProider";
import { CartContextProvider } from "@/context/cartContext";

config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cartopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <CartContextProvider>
            <Navbar />
            <main className="pt-20">{children}</main>
            <Toaster />
            <Footer />
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
